version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker-site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    volumes:
      - ./:/var/www/html
